# Generated by Django 5.2.1 on 2025-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0002_group_post_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="birth_place",
            new_name="birth_date",
        ),
    ]
