# Generated by Django 5.2.1 on 2025-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0003_rename_birth_place_profile_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_place",
            field=models.CharField(blank=True, null=True),
        ),
    ]
