# Generated by Django 5.2.1 on 2025-06-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0004_remove_profile_birth_date_profile_birth_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="quickstart.user",
            ),
        ),
    ]
